BP_TPWA/Models/Cvik.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BP_TPWA.Models
{
    public class Cvik
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CvikId { get; set; }
        [Required(ErrorMessage = "Toto pole je povinné.")]
        public string Nazev { get; set; }
        [NotMapped]
        public List<string>? PočtyOpakování { get; set; }

        [Column("PočetOpakování")]
        public string? PočetOpakováníSerialized
        {
            get => PočtyOpakování != null ? string.Join(".", PočtyOpakování) : null;
            set => PočtyOpakování = value?.Split('.').ToList();
        }
        [NotMapped]
        public List<int>? PočtySérií { get; set; }

        [Column("PočetSérií")]
        public string? PočetSériíSerialized
        {
            get => PočtySérií != null ? string.Join(",", PočtySérií) : null;
            set
            {
                if (value != null && value != "")
                {
                    PočtySérií = value?.Split(',').Select(int.Parse).ToList();
                }
            }
        }
        [NotMapped]
        public List<int>? PauzyMeziSériemi { get; set; }

        [Column("PauzaMeziSériemi")]
        public string? PauzaMeziSériemiSerialized
        {
            get => PauzyMeziSériemi != null ? string.Join(",", PauzyMeziSériemi) : null;
            set
            {
                if (value != null && value != "")
                {
                    PauzyMeziSériemi = value?.Split(',').Select(int.Parse).ToList();
                }
            }
        }

        [Required(ErrorMessage = "Toto pole je povinné.")]
        public string Partie {  get; set; }

        public string? PopisCviku { get; set; }
        [NotMapped]
        public List<string>? TypyTreninku { get; set; }

        [Column("TypTreninku")]
        public string? TypTreninkuSerialized
        {
            get => TypyTreninku != null ? string.Join(",", TypyTreninku) : null;
            set => TypyTreninku = value?.Split(',').ToList();
        }
        public string UzivatelId { get; set; }

        [ForeignKey("UzivatelId")]
        public virtual Uzivatel Uzivatel { get; set; }
        public bool cvikVytvorenUzivatelem { get; set; }
    }
}

BP_TPWA/Controllers/CvikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BP_TPWA.Data;
using BP_TPWA.Models;
using System.Security.Claims;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Globalization;
using Microsoft.AspNetCore.Authorization;
using static BP_TPWA.Controllers.TPController;

namespace BP_TPWA.Controllers
{
    [Authorize]
    public class CvikController : Controller
    {
        private readonly ApplicationDbContext _context;


        public CvikController(ApplicationDbContext context)
        {
            _context = context;
        }


        // Akce pro přidání dat do databáze
        public async Task<IActionResult> PridejData()
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (userId != null)
            {
                //BSH hlavni

                //VM podhlavni

                // Nohy

                var cvik1 = new Cvik { Nazev = "Dřepy s vlastní vahou", PopisCviku = "Zahřátí + aktivace", Partie = "Nohy", UzivatelId = userId };
                if (cvik1.TypyTreninku == null)
                {
                    cvik1.TypyTreninku = new List<string>();
                }
                if (cvik1.PočtySérií == null)
                {
                    cvik1.PočtySérií = new List<int>();
                    cvik1.PočtyOpakování = new List<string>();
                    cvik1.PauzyMeziSériemi = new List<int>();
                }
                cvik1.TypyTreninku.Add("BSHVMNohy");
                cvik1.PočtySérií.Add(3);
                cvik1.PočtyOpakování.Add("10, 10, 10");
                cvik1.PauzyMeziSériemi.Add(30);
                var cvik2 = new Cvik { Nazev = "Dřepy", PopisCviku = "Silový cvik dřep", Partie = "Nohy", UzivatelId = userId };
                if (cvik2.TypyTreninku == null)
                {
                    cvik2.TypyTreninku = new List<string>();
                }
                if (cvik2.PočtySérií == null)
                {
                    cvik2.PočtySérií = new List<int>();
                    cvik2.PočtyOpakování = new List<string>();
                    cvik2.PauzyMeziSériemi = new List<int>();
                }
                cvik2.TypyTreninku.Add("BSHVMNohy");
                cvik2.PočtySérií.Add(5);
                cvik2.PočtyOpakování.Add("12, 10, 5, 2, 1");
                cvik2.PauzyMeziSériemi.Add(80);
                var cvik3 = new Cvik { Nazev = "Legpress", PopisCviku = "Popis legpress", Partie = "Nohy", UzivatelId = userId };
                if (cvik3.TypyTreninku == null)
                {
                    cvik3.TypyTreninku = new List<string>();
                }
                cvik3.TypyTreninku.Add("BSHVMNohy");
                if (cvik3.PočtySérií == null)
                {
                    cvik3.PočtySérií = new List<int>();
                    cvik3.PočtyOpakování = new List<string>();
                    cvik3.PauzyMeziSériemi = new List<int>();
                }
                cvik3.PočtySérií.Add(4);
                cvik3.PočtyOpakování.Add("10, 10, 12, 12");
                cvik3.PauzyMeziSériemi.Add(60);

                var cvik4 = new Cvik { Nazev = "Zákopy", PopisCviku = "Popis zákopy", Partie = "Nohy", UzivatelId = userId };
                if (cvik4.TypyTreninku == null)
                {
                    cvik4.TypyTreninku = new List<string>();
                }
                cvik4.TypyTreninku.Add("BSHVMNohy");
                if (cvik4.PočtySérií == null)
                {
                    cvik4.PočtySérií = new List<int>();
                    cvik4.PočtyOpakování = new List<string>();
                    cvik4.PauzyMeziSériemi = new List<int>();
                }
                cvik4.PočtySérií.Add(4);
                cvik4.PočtyOpakování.Add("10, 10, 12, 12");
                cvik4.PauzyMeziSériemi.Add(60);

                var cvik5 = new Cvik { Nazev = "Předkopy", PopisCviku = "Popis předkopy", Partie = "Nohy", UzivatelId = userId };
                if (cvik5.TypyTreninku == null)
                {
                    cvik5.TypyTreninku = new List<string>();
                }
                cvik5.TypyTreninku.Add("BSHVMNohy");
                if (cvik5.PočtySérií == null)
                {
                    cvik5.PočtySérií = new List<int>();
                    cvik5.PočtyOpakování = new List<string>();
                    cvik5.PauzyMeziSériemi = new List<int>();
                }
                cvik5.PočtySérií.Add(4);
                cvik5.PočtyOpakování.Add("10, 10, 12, 12");
                cvik5.PauzyMeziSériemi.Add(60);
                var cvik6 = new Cvik { Nazev = "Bulharský dřep", PopisCviku = "Popis bulhart", Partie = "Nohy", UzivatelId = userId };
                if (cvik6.TypyTreninku == null)
                {
                    cvik6.TypyTreninku = new List<string>();
                }
                cvik6.TypyTreninku.Add("BSHVMNohy");
                if (cvik6.PočtySérií == null)
                {
                    cvik6.PočtySérií = new List<int>();
                    cvik6.PočtyOpakování = new List<string>();
                    cvik6.PauzyMeziSériemi = new List<int>();
                }
                cvik6.PočtySérií.Add(4);
                cvik6.PočtyOpakování.Add("10, 10, 12, 12");
                cvik6.PauzyMeziSériemi.Add(60);
                var cvik7 = new Cvik { Nazev = "Rumunský mrtvý tah", PopisCviku = "Popis rumuny", Partie = "Nohy", UzivatelId = userId };
                if (cvik7.TypyTreninku == null)
                {
                    cvik7.TypyTreninku = new List<string>();
                }
                cvik7.TypyTreninku.Add("BSHVMNohy");
                if (cvik7.PočtySérií == null)
                {
                    cvik7.PočtySérií = new List<int>();
                    cvik7.PočtyOpakování = new List<string>();
                    cvik7.PauzyMeziSériemi = new List<int>();
                }
                cvik7.PočtySérií.Add(4);
                cvik7.PočtyOpakování.Add("10, 10, 12, 12");
                cvik7.PauzyMeziSériemi.Add(60);
                var cvik8 = new Cvik { Nazev = "Hiptrusty", PopisCviku = "Popis hiptrusty", Partie = "Nohy", UzivatelId = userId };
                if (cvik8.TypyTreninku == null)
                {
                    cvik8.TypyTreninku = new List<string>();
                }
                cvik8.TypyTreninku.Add("BSHVMNohy");
                if (cvik8.PočtySérií == null)
                {
                    cvik8.PočtySérií = new List<int>();
                    cvik8.PočtyOpakování = new List<string>();
                    cvik8.PauzyMeziSériemi = new List<int>();
                }
                cvik8.PočtySérií.Add(4);
                cvik8.PočtyOpakování.Add("10, 10, 10, 10");
                cvik8.PauzyMeziSériemi.Add(60);
                var cvik9 = new Cvik { Nazev = "Lýtka ve stoje", PopisCviku = "Popis lýtka", Partie = "Nohy", UzivatelId = userId };
                if (cvik9.TypyTreninku == null)
                {
                    cvik9.TypyTreninku = new List<string>();
                }
                cvik9.TypyTreninku.Add("BSHVMNohy");
                if (cvik9.PočtySérií == null)
                {
                    cvik9.PočtySérií = new List<int>();
                    cvik9.PočtyOpakování = new List<string>();
                    cvik9.PauzyMeziSériemi = new List<int>();
                }
                cvik9.PočtySérií.Add(4);
                cvik9.PočtyOpakování.Add("10, 10, 12, 12");
                cvik9.PauzyMeziSériemi.Add(60);

                //Ramena + biceps

                var cvik11 = new Cvik { Nazev = "Tlaky na ramena - rozcvička", PopisCviku = "Zahřátí + aktivace (velmi malá nebo žádná váha)", Partie = "Ramena", UzivatelId = userId };
                if (cvik11.TypyTreninku == null)
                {
                    cvik11.TypyTreninku = new List<string>();
                    cvik11.PočtySérií = new List<int>();
                    cvik11.PočtyOpakování = new List<string>();
                    cvik11.PauzyMeziSériemi = new List<int>();
                }
                cvik11.TypyTreninku.Add("BSHVMRamBic");
                cvik11.PočtySérií.Add(2);
                cvik11.PočtyOpakování.Add("10, 10");
                cvik11.PauzyMeziSériemi.Add(30);
                var cvik12 = new Cvik { Nazev = "Tlaky na ramena s jednoručnou činkou", PopisCviku = "Tlaky na ramena", Partie = "Ramena", UzivatelId = userId };
                if (cvik12.TypyTreninku == null)
                {
                    cvik12.TypyTreninku = new List<string>();
                    cvik12.PočtySérií = new List<int>();
                    cvik12.PočtyOpakování = new List<string>();
                    cvik12.PauzyMeziSériemi = new List<int>();
                }
                cvik12.TypyTreninku.Add("BSHVMRamBic");
                cvik12.PočtySérií.Add(5);
                cvik12.PočtyOpakování.Add("12, 12, 10, 8, 5");
                cvik12.PauzyMeziSériemi.Add(60);
                var cvik13 = new Cvik { Nazev = "Upažování s jednoručnou činkou", PopisCviku = "Upažování s jednoručkama na ramena", Partie = "Ramena", UzivatelId = userId };
                if (cvik13.TypyTreninku == null)
                {
                    cvik13.TypyTreninku = new List<string>();
                    cvik13.PočtySérií = new List<int>();
                    cvik13.PočtyOpakování = new List<string>();
                    cvik13.PauzyMeziSériemi = new List<int>();
                }
                cvik13.TypyTreninku.Add("BSHVMRamBic");
                cvik13.PočtySérií.Add(4);
                cvik13.PočtyOpakování.Add("12, 12, 10, 10");
                cvik13.PauzyMeziSériemi.Add(60);

BP_TPWA/Views/Cvik/Create.cshtml
@model BP_TPWA.Models.Cvik

@{
    ViewData["Title"] = "Vytvořit cvik";
}

<h1>Vytvořit cvik</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" onsubmit="return validovatFormular()">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Nazev" class="control-label"></label>
                <input asp-for="Nazev" id="nazevcviku" class="form-control" />
                <span asp-validation-for="Nazev" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Partie" class="control-label"></label>
                <input asp-for="Partie" id="partiecviku" class="form-control" />
                <span asp-validation-for="Partie" class="text-danger"></span>
            </div>
            <div class="form-group mb-3" style="display: none;">
                <label asp-for="PočtySérií" class="control-label"></label>
                <input asp-for="PočtySérií" class="form-control" />
                <span asp-validation-for="PočtySérií" class="text-danger"></span>
            </div>
            <div class="form-group mb-3" style="display: none;">
                <label asp-for="PočtyOpakování" class="control-label"></label>
                <input asp-for="PočtyOpakování" class="form-control" />
                <span asp-validation-for="PočtyOpakování" class="text-danger"></span>
            </div>
            <div class="form-group mb-3" style="display: none;">
                <label asp-for="PauzyMeziSériemi" class="control-label"></label>
                <input asp-for="PauzyMeziSériemi" class="form-control" />
                <span asp-validation-for="PauzyMeziSériemi" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="PopisCviku" class="control-label">Popis cviku</label>
                <input asp-for="PopisCviku" id="popisek" class="form-control" />
                <span asp-validation-for="PopisCviku" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Vytvořit" class="btn btn-success mb-3" />
            </div>
        </form>
    </div>
</div>

<form asp-controller="Cvik" asp-action="Index">
    <button type="submit" class="btn btn-dark mb-3">Zpět</button>
</form>

@section Scripts {


    <script>
        function validovatFormular() {
            var vsechnyCviky = @Html.Raw(Json.Serialize(ViewBag.vsechnyCviky));
            var nazevcviku = document.getElementById("nazevcviku").value;
            var partiecviku = document.getElementById("partiecviku").value;
            var popisek = document.getElementById("popisek").value;

            if (vsechnyCviky.some(cvik => cvik.nazev === nazevcviku)) {
                alert("Tento cvik už je vytvořen");
                return false;
            }

            if (nazevcviku.length < 1 || nazevcviku.length > 200) {
                alert("Zadejte platný název cviku");
                return false;
            }

            if (partiecviku.length < 1 || partiecviku.length > 100) {
                alert("Zadejte platný název partie cviku");
                return false;
            }

            if (popisek.length < 1 || popisek.length > 5000) {
                alert("Zadejte platný popisek s který má maximálně 5000 znaků.");
                return false;
            }


            return true;
        }
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BP_TPWA/Views/Cvik/Delete.cshtml
@model BP_TPWA.Models.Cvik

@{
    ViewData["Title"] = "Smazat cvik";
}



<h3>Opravdu chcete smazat tento cvik?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazev)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazev)
        </dd>
        <dt class = "col-sm-2">
            Popis cviku
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PopisCviku)
        </dd>
    </dl>
    
    <div class="button-container-cus1">
        <form asp-action="Delete">
            <input type="hidden" asp-for="CvikId" />
            <input type="submit" value="Smazat" class="btn btn-danger custom-mr" /> 
        </form>

        <form asp-controller="Cvik" asp-action="Index" method="get">
            <button type="submit" class="btn btn-dark">Zpět</button>
        </form>
    </div>
</div>

BP_TPWA/Views/Cvik/Edit.cshtml
@model BP_TPWA.Models.Cvik

@{
    ViewData["Title"] = "Upravit cvik";
}

<h1>Upravit cvik</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" onsubmit="return validovatFormular()">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CvikId" />
            <div class="form-group">
                <label asp-for="Nazev" class="control-label"></label>
                <input asp-for="Nazev" id="nazevcviku" class="form-control" />
                <span asp-validation-for="Nazev" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PopisCviku" class="control-label">Popis cviku</label>
                <input asp-for="PopisCviku" id="popisek" class="form-control" />
                <span asp-validation-for="PopisCviku" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Partie" class="control-label">Partie</label>
                <input asp-for="Partie" id="partiecviku" class="form-control" />
                <span asp-validation-for="Partie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Uložit" class="btn btn-warning mb-3" />
            </div>
        </form>
    </div>
</div>

<form asp-controller="Cvik" asp-action="Index" method="get">
    <button type="submit" class="btn btn-dark">Zpět</button>
</form>

@section Scripts {

@*     <script>
        function validovatFormular() {
            var vsechnyCviky = @Html.Raw(Json.Serialize(ViewBag.vsechnyCviky));
            var nazevcviku = document.getElementById("nazevcviku").value;
            var partiecviku = document.getElementById("partiecviku").value;
            var popisek = document.getElementById("popisek").value;

            if (vsechnyCviky.some(cvik => cvik.Nazev === nazevcviku.value)) {
                alert("Tento cvik už je vytvořen");
                return false;
            }

            if (nazevcviku.length < 1 || nazevcviku.length > 200) {
                alert("Zadejte platný název cviku");
                return false;
            }

            if (partiecviku.length < 1 || partiecviku.length > 100) {
                alert("Zadejte platný název partie cviku");
                return false;
            }

            if (popisek.length < 1 || popisek.length > 5000) {
                alert("Zadejte platný popisek s který má maximálně 5000 znaků.");
                return false;
            }

            return true;
        }
    </script> *@

    <script>
        function validovatFormular() {
            var vsechnyCviky = @Html.Raw(Json.Serialize(ViewBag.vsechnyCviky));
            var cvikNaEdit = @Html.Raw(Json.Serialize(ViewBag.cvikNaEdit));

            var nazevcviku = document.getElementById("nazevcviku").value;
            var partiecviku = document.getElementById("partiecviku").value;
            var popisek = document.getElementById("popisek").value;

            var cvikSeStejnymNazvem = vsechnyCviky.filter(cvik => cvik.nazev === nazevcviku);
            //console.log(cvikSeStejnymNazvem);
            if (cvikSeStejnymNazvem) {
                if (cvikSeStejnymNazvem.length === 1) {
                    if (cvikSeStejnymNazvem[0].cvikId === cvikNaEdit.cvikId) {

                    } else {
                        alert("Tento cvik už je vytvořen");
                        return false;
                    }
                } 
            }

            // if (vsechnyCviky.some(cvik => cvik.nazev === nazevcviku)) {
            //     alert("Tento cvik už je vytvořen");
            //     return false;
            // }

            if (nazevcviku.length < 1 || nazevcviku.length > 200) {
                alert("Zadejte platný název cviku");
                return false;
            }

            if (partiecviku.length < 1 || partiecviku.length > 100) {
                alert("Zadejte platný název partie cviku");
                return false;
            }

            if (popisek.length < 1 || popisek.length > 5000) {
                alert("Zadejte platný popisek s který má maximálně 5000 znaků.");
                return false;
            }


            return true;
        }
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BP_TPWA/Views/Cvik/Index.cshtml
@model IEnumerable<BP_TPWA.Models.Cvik>

@{
    ViewData["Title"] = "Databáze cviků";
}

<h1>Databáze cviků</h1>



<div class="form-group">
    <label for="partieSelect">Vyberte Partii:</label>
    <select class="form-control" id="partieSelect">
        <option value="all">Všechny</option>
        @foreach (var partie in Model.Select(c => c.Partie).Distinct())
        {
            <option value="@partie">@partie</option>
        }
    </select>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nazev)
            </th>
            <th>
                Popis cviku
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        if (item.UzivatelId == @ViewBag.uzivatelId)
        {

                <tr id="@Html.DisplayFor(modelItem => item.Partie)">
                <td>
                        @Html.DisplayFor(modelItem => item.Nazev)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PopisCviku)
                </td>
                <td>
                    @if (item.cvikVytvorenUzivatelem == true)
                    {
                        <div class="button-container-cus1">
                            <form asp-controller="Cvik" asp-action="Edit" asp-route-id="@item.CvikId" method="get">
                                <button type="submit" class="btn btn-outline-warning btn-sm custom-mr">Upravit</button>
                            </form>
                            <form asp-controller="Cvik" asp-action="Delete" asp-route-id="@item.CvikId" method="get">
                                <button type="submit" class="btn btn-outline-danger btn-sm">Smazat</button>
                            </form>
                        </div>
                    }
                </td>
            </tr>
        }
}
    </tbody>
</table>

<div class="button-container-cus">
    <form method="get" action="/TP/Index">
        <button class="btn btn-dark mb-3" type="submit">Přesunout se na plán</button>
    </form>
    <form method="get" action="/Cvik/Create">
        <button class="btn btn-outline-dark float-right-custom mb-3" type="submit">Vytvoř si svůj cvik</button>
    </form>
</div>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var partieSelect = document.getElementById('partieSelect');
        partieSelect.addEventListener('change', function () {
            var selectedPartie = this.value;
            var rows = document.querySelectorAll('tbody tr');
            rows.forEach(function (row) {
                var rowId = row.getAttribute('id');
                if (selectedPartie === rowId || selectedPartie === 'all') {
                    row.style.display = '';
                } else {
                    row.style.display = 'none';
                }
            });
        });
    });
</script>

BP_TPWA/Views/Cvik/NastavitData.cshtml
@model IEnumerable<BP_TPWA.Models.Cvik>

@{
    ViewData["Title"] = "Nastavit Data";
}

@foreach (var item in Model)
{
    <h1>Nastavit Data pro cvik @Html.DisplayFor(modelItem => item.Nazev)</h1>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form method="post" action="/Cvik/UlozitPridaneData" onsubmit="return validovatFormular()">
                <input type="hidden" name="cvikId" value="@item.CvikId" />
                <input type="hidden" name="datum" value="@ViewBag.datum" />
                <label for="pocetSerií" class="form-label mt-4">Počet sérií (př. 3)</label>
                <input type="text" class="form-control" id="pocetSerií" min="1" max="15" name="pocetSerií" placeholder="Počet sérií" required />

                <label for="opakování" class="form-label mt-4">Opakování v sériích (př. 12, 10, 8)</label>
                <input type="text" class="form-control" id="opakování" name="opakování" placeholder="Opakování v sériích" required />

                <label for="pauza" id="pauzaText" class="form-label mt-4">Pauza mezi sériemi (s) (př. 60)</label>
                <input type="text" class="form-control" id="pauza1" min="0" max="300" name="pauza" placeholder="Pauza mezi sériemi (s)" required />

                <button type="submit" class="btn btn-outline-success mt-3 mb-3">Uložit</button>
            </form>
        </div>
    </div>

    <form method="get" action="/TP/Index">
        <button class="btn btn-dark mb-3" type="submit">Zpět na plán</button>
    </form>
}
@section Scripts {
    <script>
        document.getElementById("pocetSerií").addEventListener("change", function () {
            var serie = this.value;
            var pauzaDiv = document.getElementById("pauza1");
            var pauzaText = document.getElementById("pauzaText");
            if (parseInt(serie) === 1) {
                pauzaDiv.style.display = "none";
                pauzaText.style.display = "none";
                pauzaDiv.value = 0;
            } else {
                pauzaDiv.style.display = "block";
                pauzaText.style.display = "block";
            }
        });

        function validovatFormular() {
            var pocetSerií = parseInt(document.getElementById("pocetSerií").value);
            var opakování = document.getElementById("opakování").value;
            var pauza = parseInt(document.getElementById("pauza1").value);

            if (pocetSerií < 1 || pocetSerií > 15) {
                alert("Zadejte platný počet sérií");
                return false;
            }

            if (pauza < 0 || pauza > 300) {
                alert("Zadejte platnou pauzu kratší než 5 minut");
                return false;
            }

            var opakováníArray = opakování.split(',').map(function (item) {
                var parsedValue = parseInt(item.trim());
                if (!isNaN(parsedValue)) {
                    return parsedValue;
                }
            }).filter(function (item) {
                return typeof item === 'number' && item > 0 && item < 50;
            });

            if (opakováníArray.length !== pocetSerií) {
                alert("Zadejte platný počet opakování ve správném formátu");
                return false;
            }

            return true;
        }
    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BP_TPWA/Views/Cvik/Playlisty.cshtml
@model BP_TPWA.Models.Cvik

@{
    ViewData["Title"] = "Playlisty";
}

<h1 class="text-center">Zde jsou odkazy na předdělané playlisty na Spotify</h1>

<hr />

<div class="container">
    <h4>Rádiovky</h4>
    <p><a href="https://open.spotify.com/playlist/1I5ti83R2wyTzKRhj3chOO?si=a472047bcf8b4592">Odkaz na playlist</a></p>
    <hr />
    <h4>Rap</h4>
    <p><a href="https://open.spotify.com/playlist/4e1nbbpxbMz18kDO4RU74u?si=f5f7371a922e4b89">Odkaz na playlist</a></p>
    <hr />
    <h4>Rock</h4>
    <p><a href="https://open.spotify.com/playlist/3BYdPptQ5Cnj2Kta1FSl1n?si=39cae71a2dfa4cfe">Odkaz na playlist</a></p>
    <hr />
    <h4>Motivační hudba</h4>
    <p><a href="https://open.spotify.com/playlist/3pN5mJloTCf4W4sPYycvqf?si=ae0568730cb84988">Odkaz na playlist</a></p>
    <hr />

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}